services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    platform: linux/amd64
    volumes:
      - ..:/workspaces:cached
    command: sleep infinity
    networks:
      - dev-network

networks:
  dev-network:
